### ISSUE TITLE
Where is pygram11 in performance compared to fast-histogram?

### ISSUE THREAD

**Issue by tim-hilt** [douglasdavis/pygram11#10]
Basically the title.

I want to go for raw speed only and don't care for much more than being able to specify bin-edges and getting back a numpy-array from the function that calculates the histogram.

To give a little more context: It could be, that i will have to calculate a histogram of 1'000'000 bins, where each bin is 1000 integers wide. I would have to fill 1000 values in those bins. Can you tell me if this is possible with pygram11?

**Comment by douglasdavis** [comment]
The [benchmarks](https://pygram11.readthedocs.io/en/stable/bench.html) page contains some results comparing pygram11 performance to fast-histogram w.r.t. histograms with fixed width bins. If you're input data is 1000 values I would expect fast-histogram to be more performant. I'm not sure if I understand your problem correctly. By 1,000,000 bins that are 1,000 ints wide do you mean a fixed width histogram with bin width equal to 1,000? If so here's a solution with both libraries:
```python
>>> import numpy as np
>>> import fast_histogram
>>> import pygram11
>>> one_bil = 1_000_000_000  # xmax 
>>> one_mil = 1_000_000      # one million bins
>>> x = np.random.random_integers(0, one_bil, 1000) # 1k random values
>>> result1 = fast_histogram.histogram1d(x, bins=one_mil, range=(0, one_bil))
>>> result2, err2 = pygram11.histogram(x, bins=one_mil, range=(0, one_bil))
>>> np.allclose(result1, result2)
True
```

**Comment by tim-hilt** [comment]
First of all: Thank you for a very quick reply and an awesome try-out code. I tried specifying bins as a range, which doesn't look nearly as clean as using the `range`-parameter. You absolutely got my application right and i tried it out on `numpy.histogram`, `fast_histogram.histogram1d` and `pygram11.histogram`. Here is an image with my results:

![Screenshot_20210114_174214](https://user-images.githubusercontent.com/16037579/104621382-55d16e00-5690-11eb-9b81-9af3dd6c30f2.png)

so there was a near to 2x speedup with `pygram11`, while using `fast_histogram` was about 24x faster than the Numpy-baseline. Doesn't this collide with the benchmarks? I'm very surprised of this outcome!

**Comment by douglasdavis** [comment]
I do expect fast_histogram to be faster than pygram11 for a sample size of less than about 10,000 (in the benchmarks for a fixed 1D histogram pygram11 performs better than fast_histogram somewhere around `len(x) > 5000`, for arrays of floats). pygram11 is optimized for very large (weighted) datasets (I wrote it when I needed to create histograms where the input data was at least `len(x) > 100,000` and I needed to track the variance in the bin for weighted input). Given that, any arrays passed to pygram11 that are not `np.float32` or `np.float64` are converted (so extra time is taken to convert integer arrays to float arrays). Perhaps it would be useful to implement into the backend native integer histogramming. For your problem it seems that fast_histogram is the most performant histogramming implementation. Here's a use case where pygram11 becomes the most performant (floating point data with length 500,000):
```python
Python 3.9.1 (default, Dec 11 2020, 18:47:23) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numpy as np

In [2]: import fast_histogram

In [3]: import pygram11

In [4]: x = np.random.randn(500000)

In [5]: bins = 1000

In [6]: xmin = -4.0

In [7]: xmax = 4.0

In [8]: %timeit np.histogram(x, bins=bins, range=(xmin, xmax))
5.57 ms ± 46.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [9]: %timeit pygram11.histogram(x, bins=bins, range=(xmin, xmax))
322 µs ± 2.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [10]: %timeit fast_histogram.histogram1d(x, bins=bins, range=(xmin, xmax))
799 µs ± 470 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [11]: x.dtype
Out[11]: dtype('float64')
```

**Comment by tim-hilt** [comment]
Ah ok, wow! That's really interesting and a good distinction. I think, that for the moment i will use `fast_histogram`, however i already see myself coming back to `pygram11` in the future. There *will* be a use-case.

Thanks for making this project happen and thanks for all your support and explanations.

**Comment by douglasdavis** [comment]
I'm glad to see you might be finding the project useful! I went a ahead and added a small note to the benchmark documentation pointing to this issue in case other users have a similar experience.

**Comment by douglasdavis** [comment]
Hi @tim-hilt the latest version of pygram11 (0.11.0, released today) now performs similar to fast-histogram for the problem you described in this issue:

```python
In [10]: %timeit res_pg, _ = pg.histogram(x, bins=one_mil, range=(0, one_bil))
443 µs ± 4.81 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [11]: %timeit res_np, _ = np.histogram(x, bins=one_mil, range=(0, one_bil))
3.25 ms ± 42.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [12]: %timeit res_fh = fh.histogram1d(x, bins=one_mil, range=(0, one_bil))
438 µs ± 3.27 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [13]: pg.__version__
Out[13]: '0.11.0'
```

The backend code now covers more data types and also takes care to avoid wasting CPU cycles on counting weights when it's unncessary and avoid parallelizing loops when it's not advantageous. Parallelization thresholds are configurable now as well.

**Comment by tim-hilt** [comment]
Ah, wow! :rocket: Thanks for the heads up. That makes `pygram11` clearly favorable over `fast_histogram` atm
